### ISSUE TITLE
Personal Goals Guide link is broken

### ISSUE THREAD

**Issue by jwithington** [una/personal-goals#16]
Hi Una,

I noticed that your link where folks can read more about your goals is broken.  The link in question:

http://una.im/personal-goals-guide/

If I could have found a new spot where it lives I would have done a pull request for you. :grinning: 

Incidentally: I heard about this project on Developer Tea — it's _amazing_. I think I'm going to start my own!

**Comment by una** [comment]
try it without the trailing slash: http://una.im/personal-goals-guide <http://una.im/personal-goals-guide>

:) Cheers
Una

**Comment by jwithington** [comment]
:+1: :grinning:
