### ISSUE TITLE
what happened since august?

### ISSUE THREAD

**Issue by sw-yx** [una/personal-goals#24]
Just stopping by and wondering what happened since august, no weekly updates since then! but glad you're still alive with all the happy moments!

**Comment by BartoszDabek** [comment]
I know it's old but I'm also curious, why there is no updates? 
I found it very motivational and cross fingers that you will continue on it!

**Comment by una** [comment]
Sorry y'all! I started doing my weekly todos in my physical bullet journal. I'm still at it, but it's a bit nicer of an experience now for me to get offline and think about my weekly goals <3

**Comment by swyxio** [comment]
A L W A Y S O N L I N E

/s

glad you are being productive on the #bujo
